/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicios;

/**
 *
 * @author mark
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Numero1Cbx = new javax.swing.JTextField();
        Numero2Cbx = new javax.swing.JTextField();
        ResultadoCbx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SumaBttn = new javax.swing.JRadioButton();
        RestaBttn = new javax.swing.JRadioButton();
        MultiBttn = new javax.swing.JRadioButton();
        DivisionBttn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero 1:");

        jLabel2.setText("Numero 2:");

        jLabel3.setText("Resultado:");

        buttonGroup1.add(SumaBttn);
        SumaBttn.setText("Suma");
        SumaBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaBttnActionPerformed(evt);
            }
        });

        buttonGroup1.add(RestaBttn);
        RestaBttn.setText("Resta");
        RestaBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaBttnActionPerformed(evt);
            }
        });

        buttonGroup1.add(MultiBttn);
        MultiBttn.setText("Multiplicacion");
        MultiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiBttnActionPerformed(evt);
            }
        });

        buttonGroup1.add(DivisionBttn);
        DivisionBttn.setText("Division");
        DivisionBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Numero1Cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResultadoCbx)
                            .addComponent(Numero2Cbx)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MultiBttn)
                            .addComponent(SumaBttn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RestaBttn)
                            .addComponent(DivisionBttn))
                        .addGap(22, 22, 22)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Numero1Cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Numero2Cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SumaBttn)
                    .addComponent(RestaBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MultiBttn)
                    .addComponent(DivisionBttn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SumaBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaBttnActionPerformed
       int n1 = Integer.parseInt(Numero1Cbx.getText());
       int n2 = Integer.parseInt(Numero2Cbx.getText());
       
       int resultado = n1 + n2;
       
       ResultadoCbx.setText("" + resultado);
    }//GEN-LAST:event_SumaBttnActionPerformed

    private void RestaBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaBttnActionPerformed
       int n1 = Integer.parseInt(Numero1Cbx.getText());
       int n2 = Integer.parseInt(Numero2Cbx.getText());
       
       int resultado = n1 - n2;
       
       ResultadoCbx.setText("" + resultado);
    }//GEN-LAST:event_RestaBttnActionPerformed

    private void MultiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiBttnActionPerformed
       int n1 = Integer.parseInt(Numero1Cbx.getText());
       int n2 = Integer.parseInt(Numero2Cbx.getText());
       
       int resultado = n1 * n2;
       
       ResultadoCbx.setText("" + resultado);
    }//GEN-LAST:event_MultiBttnActionPerformed

    private void DivisionBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionBttnActionPerformed
       double n1 = Integer.parseInt(Numero1Cbx.getText());
       double n2 = Integer.parseInt(Numero2Cbx.getText());
       
       double resultado = n1 / n2;
       
       ResultadoCbx.setText("" + resultado);
    }//GEN-LAST:event_DivisionBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DivisionBttn;
    private javax.swing.JRadioButton MultiBttn;
    private javax.swing.JTextField Numero1Cbx;
    private javax.swing.JTextField Numero2Cbx;
    private javax.swing.JRadioButton RestaBttn;
    private javax.swing.JTextField ResultadoCbx;
    private javax.swing.JRadioButton SumaBttn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
